# Generated by Django 5.0.1 on 2024-03-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_tag',
            new_name='tag',
        ),
    ]
