# Generated by Django 5.0.1 on 2024-03-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_tag_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exerpt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
